# Кейс NEET-молодежи: могут ли некогнитивные навыки помочь?

## Постановка проблемы

Способность найти достойную работу, соответствующую полученному образованию, представляет собой одну из ключевых задач, стоящих перед молодежью на этапе перехода от подросткового возраста к взрослой жизни. В то время как одни молодые люди успешно реализуют накопленный в системе формального образования человеческий капитал, другие начинают карьерный путь с должностей, не соответствующих их ожиданиям и квалификации. Существуют и те, кто не учится, не развивает профессиональные навыки и не участвует в экономической деятельности. Эта категория обозначается как молодежь NEET (англ. *Not in Education, Employment or Training*) — молодые люди в возрасте 15–24 лет, которые не получают образования, не проходят профессиональное обучение и не работают. На сегодняшний день уровень NEET рассматривается как индикатор эффективности перехода от учебы к занятости, уровня социальной инклюзии молодежи и ее участия в социально-экономической жизни общества \[\@elder2015\].

Молодежь NEET представляет собой одну из наиболее уязвимых групп на рынке труда и является объектом приоритетного внимания социальной политики в странах с различным уровнем дохода, что закреплено в глобальной повестке устойчивого развития. В частности, в рамках Целей устойчивого развития (ЦУР) уровень молодежи NEET в возрасте 15–24 лет включен в число ключевых индикаторов ЦУР 8, связанной с достойной занятостью и экономическим ростом. Согласно последним данным МОТ, ответственной за данный индикатор, даже в странах с высоким уровнем дохода каждый десятый молодой человек испытывает трудности при переходе из системы образования на рынок труда. В России, согласно данным Росстата, уровень NEET составляет 16%, что сопоставимо с показателями экономически развитых стран. При этом сопоставление с другими данными мониторинга ЦУР показывает, что такой уровень скорее обусловлен недостаточной инклюзивностью рынка труда, нежели ограничениями в доступе к образованию: по данным Института статистики ЮНЕСКО, доля молодежи, не охваченной программами старшей ступени общего среднего образования (16–18 лет), составляет лишь 2,5%, что является одним из самых низких показателей в мире. Тем не менее, молодые люди сталкиваются с трудностями при выходе на рынок труда, и, как следствие, государства сталкиваются с необходимостью разрабатывать меры поддержки данной категории в рамках политики занятости.

Причины распространённости явления NEET могут быть связаны как с институциональными факторами, отражающими эффективность системы образования и спроса на квалифицированный труд (см. \[\@amendola2022; \@bal-domanska2022; \@maynou2022; \@bingol2020\]), так и с характеристиками предложения труда — индивидуальными чертами экономических агентов. Помимо базовых демографических характеристик, таких как пол и возраст, к ним традиционно относят уровень образования и наличие профессионального опыта. Существующие исследования подчеркивают, что ранняя занятость является важным фактором, снижающим вероятность попадания в категорию NEET \[\@ballo2022; \@berlin2021\]. Очевидно, что такие факторы, как образование и опыт работы, хорошо известны экономистам как ключевые предикторы в уравнении заработной платы Минсера, традиционно используемом для оценки отдачи от образования. Однако растущий интерес экономистов к имеющей психологичекскую природу индивидуальной гетерогенности, имеющей психологическую природу и в классических моделях трактуемой как “ненаблюдаемые способности” (ошибка модели). Признание того, что ряд факторов, помимо образования и опыта, объясняют различия в доходах т других показателях экономического успеха, привело к формированию нового исследовательского направления, изучающего влияние личностных черт на результаты на рынке труда и за его пределами \[\@almlund2011; \@lindqvist2011; \@glewwe2017; \@bowles2001; \@mueller2006; \@carneiro2007; \@kniesner2008\].

В этом контексте изучение связи между некогнитивными навыкам, которые апроксимируются личностными характеристиками, и уязвимым статусом молодежи в переходе из системы образования на рынок труда, операционализированным в индикаторе NEET, представляет растущий исследовательский интерес. В то время какбольшее количество экономических исследований посвящено анализу этих навыков в контексте непрерывного образования \[\@laible2020\], статуса занятости \[\@heckman2011\], или уровня заработной платы \[\@almlund2011; \@lindqvist2011\], внимание к некогнитивным навыкам в контексте молодежи NEET в исследовательской повестке по-прежнему ограничено. В связи с этим настоящая глава сосредоточена на следующем исследовательском вопросе: *наблюдается ли разрыв в уровне сформированности некогнитивных навыков в зависимости от принадлежности молодежи к статусу NEET? Иными словами, целью исследования является оценка степени отставания молодежи NEET от их сверстников по уровню некогнитивных характеристик, которые необходимы для инклюзивного социально-экономического участия молодежи в условиях современной экономики.*

график для профиля - возраст на оси х и на оси у два шарика - 2016 т 2019 год с долей молодежи НИТ

Смысл в том что в возрастной когорте 15-24 коэффициент скорее будет указывать на выпадение из системы образования

Четыре статуса - нит безработные, нит-неактивные, учатся, работают

<https://www.tandfonline.com/doi/full/10.1080/02673843.2024.2306256#d1e163>

<https://www.tandfonline.com/doi/full/10.1080/02673843.2024.2331576#d1e142>
