# Интра-семейная вариация в некогнитивных навыках братьев и сестер

## Постановка проблемы

Двойная постановка проблемы

С однеой стороны посмиотреть на роль семейной среды в вариации некогнитивных навыков между сиблингами.

С другой - посмотреть эффект некогнитивных навыков на получение высшего образования и трудоусмтройства с учетом внутрисемейного дизайна - иными словыами полностью игнорируя преимуцщесмтво в сеемйных характеристиках вроде уровня образования родителей или дохода семьи на социально-экономитческие результаты индивидов

Новизна исследования в этом плане также в двух контекстах

с одной стороны к нашемсу сведению это первое исследование в экономическом ключе которое рассматривает некогнитивные навыки через внутри-семейную призму

как следствие, и изучение влияния некогнитивных навыков на социально эконормические результаты в системе образования и на рынке труда также игнорировало внутри-семейный дизайн

хотя предпринятые стратегии верификации изыскивали разные способы контроля эндогености некогниттивных навыков и результатов в системе образования и на рынкуе труда ввиду социально экономического статуса семьи, внутьрисемейный дизайн дает новую перспективу на эффекты некогнитивных навыков - он смравнивает индивидов которые не разнятся в базовых преимуществах преуспеть на рынке труда или в образовании ввиду статусных достижений родителей

## Обзор литературы

## Данные