project:
  type: book
  output-dir: docs

book:
  title: ""
  author: ""
  date: ""
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_lit_rev.qmd
    - 03_data.qmd
    - 04_ncs_empl.qmd
    - 05_ncs_wages.qmd
    - 06_ncs_job_satisf.qmd
    - 07_concl.qmd
    - references.qmd

bibliography: references_sorted.bib

format:
  html:
    theme: cosmo
  pdf:
    latex-engine: xelatex
    mainfont: "Times New Roman"          # body text
    sansfont: "Times New Roman"          # sans-serif text (used in headings by some classes)
    monofont: "Courier New"              # monospace text (code blocks, etc.)
    titlefont: "Times New Roman"         # <- this works in `quarto` >=1.5
    documentclass: scrreprt
    number-sections: true
    lang: ru-RU
    fontsize: 12pt                       # <- set font size here
    toc: false               # ← suppress automatic TOC
    lof: false               # ← suppress automatic list of figures  
    lot: false               # ← suppress automatic list of tables
    include-in-header: 
      text: |
        \usepackage{pdflscape}
  docx: 
    number-sections: true
    mainfont: "Times New Roman"          # body text
    sansfont: "Times New Roman"          # sans-serif text (used in headings by some classes)
    monofont: "Courier New"              # monospace text (code blocks, etc.)
    titlefont: "Times New Roman"         # <- this works in `quarto` >=1.5
    toc: true                            # ← enable automatic TOC
    lof: true                            # ← enable automatic list of figures
    lot: true                            # ← enable automatic list of tables


lang: ru-RU
citeproc: true
biblio-style: bwl-FU
csl: "apa-with-abstract.csl"

editor: visual

execute:
  echo: false
  warning: false
  message: false
  error: false  # optional

