# Список таблиц

**Глава 3. Данные**

Таблица 3.1. Психометрический анализ некогнитивных навыков: открытость новому опыту

Таблица 3.2. Психометрический анализ некогнитивных навыков: добросовестность

Таблица 3.3. Психометрический анализ некогнитивных навыков: экстраверсия

Таблица 3.4. Психометрический анализ некогнитивных навыков: дружелюбие

Таблица 3.5. Психометрический анализ некогнитивных навыков: эмоциональная стабильность

Таблица 3.6. Характеристика выборки

Таблица 3.7. Описательная статистика переменных, описывающих успех перехода от учебы к работе

Таблица 3.8. Классификация молодежи по роду занятий в соответствии с МСКЗ-08

Таблица 3.9. Описательная статистика почасовой заработной платы трудоустроенной молодежи до 30 лет в РМЭЗ, цены 2019 года

Таблица 3.10. Дескриптивная статистика по переменным общей и компонентной удовлетворённости работой

Таблица 3.11. Описательные статистики некогнитивных навыков

**Глава 4. Путь от учебы к работе: способствуют ли некогнитивные навыки трудоустройству молодежи?**

Таблица 4.1. Коэффициенты внутриклассовой корреляции базовой модели со смешанными эффектами

Таблица 4.2. Фиксированные (неварьирующиеся) коэффициенты смешанных моделей с случайными интерсептами по возрасту, индивидуальному идентификатору и региону: (1) Модель с случайными интерсептами и некогнитивными навыками, (2) Модель с случайными интерсептами, некогнитивными навыками и контрольными переменными

Таблица 4.3. Фиксированные (неварьирующиеся) коэффициенты смешанных моделей с случайными наклонами по некогнитивным навыкам в разрезе: (1) количества лет с момента окончания наивысшего уровня образования, (2) квинтиля среднедушевого дохода домохозяйства в возрасте 15/16 лет, (3) уровня образования и (4) пола

Таблица 4.4. Фиксированные (неварьирующиеся) коэффициенты смешанных моделей выбора профессии: (1) Высококвалифицированные работники, занятые интеллектуальным трудом, (2) Высококвалифицированные работники, занятые интеллектуальным трудом, со случайными коэффициентами некогнитивных навыков по социально-экономическому статусу

Таблица 4.5. Результаты регрессионной модели со смешанными эффектами, модель несоответствия уровня образования выполняемой работе (избыточной квалификации)

**Глава 5. Отдача от некогнитивных навыков: насколько она гетерогенна в зависимости от уровня оплаты труда?**

Таблица 5.1. Результаты квантильной смешанной модели: отдача от некогнитивных навыков, базовая модель (без образования) с учетом селекции в занятость через инверсные вероятностные веса

Таблица 5.2. Отдача от некогнитивных навыков, результаты квантильной смешанной модели, расширенная модель (с учетом образования)

Таблица 5.3. Отдача от некогнитивных навыков, результаты квантильной смешанной модели с обратными вероятностными весами и взаимодействием пола и некогнитивных характеристик

Таблица 5.4. Отдача от некогнитивных навыков, медианные модели с обратными вероятностными весами по возрастным группам

**Глава 6. Эффект некогнитивных навыков на удовлетворенность работой: варьируется ли он в зависимости от уровня заработной платы?**

Таблица 6.1. Внутриклассовые коэффициенты корреляции базовой смешанной модели: удовлетворённость работой по случайным эффектам (индивидуальный ID, регион, квинтильная группа заработной платы)

Таблица 6.2. Смешанные регрессионные модели удовлетворённости работой: 1) социоэкономические факторы, 2) социоэкономические факторы и некогнитивные навыки, 3) модель со случайными наклонами некогнитивных навыков по квинтилям заработной платы

Таблица 6.3. Результаты смешанных моделей регрессии удовлетворенности: 1) возможностями карьерного роста, 2) условиями труда, 3) заработной платой