# Список рисунков

**Глава 3. Данные**

Рисунок 3.1. Шкала Лайкерта единичных вопросов для измерения некогнитивных навыков Большой пятерки в РМЭЗ среди молодежи 15-29 лет, данные 25-й и 28-й волн

Рисунок 3.2. Матрица корреляций некогнитивных навыков (Pearson's r)

Рисунок 3.3. Матрица корреляций общей удовлетворённости работой и её отдельных компонентов

**Глава 4. Путь от учебы к работе: способствуют ли некогнитивные навыки трудоустройству молодежи?**

Рисунок 4.1. Прогнозируемая вероятность влияния возраста (случайный интерсепт) на занятость по полу, базовая модель со смешанными эффектами

Рисунок 4.2. Коэффициенты вероятности влияния некогнитивных навыков на занятость по квинтилям среднедушевого дохода домохозяйства (случайные наклоны модели со смешанными эффектами)

Рисунок 4.3. Коэффициенты влияния некогнитивных навыков на вероятность занятости в разрезе уровня образования, варьирующиеся коэффициенты модели со смешанными эффектами

Рисунок 4.4. Коэффициенты влияния некогнитивных навыков на вероятность занятости по полу, варьирующиеся коэффициенты модели со смешанными эффектами

Рисунок 4.5. Коэффициенты вероятности эффекта некогнитивных навыков на занятость по квинтилям среднедушевого дохода домохозяйства: случайные кривые смешанной модели

**Глава 5. Отдача от некогнитивных навыков: насколько она гетерогенна в зависимости от уровня оплаты труда?**

Рисунок 5.1. Отдача от некогнитивных навыков по уровням образования и квантилям заработной платы, результаты квантильных смешанных моделей с использованием обратных вероятностных весов

Рисунок 5.2. Эффект возраста на логарифм почасовой оплаты труда: результаты обобщённой аддитивной регрессии

**Глава 6. Эффект некогнитивных навыков на удовлетворенность работой: варьируется ли он в зависимости от уровня заработной платы?**

Рисунок 6.1. Влияние логарифма почасовой заработной платы на общую удовлетворённость работой, результаты GAM-регрессии

Рисунок 6.2. Случайные наклоны некогнитивных навыков на удовлетворённость работой, результаты смешанной регрессии