---
title: "Некогнитивные навыки в структуре человеческого капитала: теория, измерение и экономическое значение"
author: 
 - name: Аванесян Карен Алексеевич
   affiliation: Southern Federal University
   email: avanesian@sfedu.ru
format: 
  docx:
    geometry: 
      - top=30mm
      - left=30mm
      - right=30mm
documentclass: article
lang: ru-RU
editor: visual
bibliography: references_sorted.bib  
biblio-style: bwl-FU
csl: "apa-with-abstract.csl"
---

**Аннотация**

В последние два десятилетия некогнитивные навыки — устойчивые личностные характеристики, влияющие на экономическре поведение и интеграцию в общественные институты образования и рынка труда — заняли центральное место в исследованиях человеческого капитала. Настоящая статья предлагает обзор эволюции концепта некогнитивных навыков в экономической литературе, подчеркивая их значимость для образовательных и трудовых результатов индивидов. Анализ охватывает теоретические дискуссии о природе и измерении этих навыков, включая модель «Большой пятёрки» и альтернативные таксономии. Особое внимание уделено критике существующих подходов, сложности операционализации и рискам редукционизма при попытках интеграции личностных черт в государственную политику. Также рассматриваются эмпирические исследования на российском материале, показывающие неоднородную отдачу от некогнитивных навыков на рынке труда и в образовании. В завершение обосновывается необходимость перехода от психометрических конструкций к прикладным моделям, пригодным для разработки системы государственного регулирования и эффективности таргетированных интервенций.

**Abstract**

Over the past two decades, non-cognitive skills — stable personality traits that influence economic behavior and integration into key institutes such as education and the labor market —have taken center stage in human capital research. This article reviews the evolution of the concept of non-cognitive skills in the economic literature, emphasizing their relevance for individual educational and labor market outcomes. The analysis covers theoretical debates on the nature and measurement of these skills, including the Big Five personality model and alternative taxonomies. Particular attention is given to critiques of existing approaches, the challenges of operationalization, and the risks of reductionism when attempting to incorporate personality traits into public policy. The article also examines empirical studies based on the international and Russian data, which reveal the heterogeneous returns to non-cognitive skills in both education and the labor market. In conclusion, the paper argues for a shift from purely psychometric constructs toward applied models suitable for informing social policy and the effectiveness of targeted interventions.

**ключевые слова:** некогнитивные навыки; человеческий капитал; Большая пятерка; рынок труда.

**key words:** non-cognitive skills; human capital; Big Five personality traits; labor market.

**JEL codes:** J24, I24

\newpage

## Введение

Вопросы экономического неравенства и успеха на рынке труда всё чаще рассматриваются в контексте расширенного понимания человеческого капитала, выходящего за рамки исключительно формального образования и когнитивных способностей. За последние два десятилетия в экономической науке оформилась новая агенда, признающая ключевую роль так называемых некогнитивных навыков — устойчивых личностных характеристик, формирующих паттерны мышления и поведения и влияющих на способность индивида достигать целей и интегрироваться в общественные и экономические институты. Современная экономическая литература трактует некогнитивные навыки как еще одно измерение человеческого капитала, в дополнение к квалификациям, закрепленным формальным образованием [@heckman2006; @cunha2007; @humphries2017; @non-cogn2018]. В отличие от когнитивных навыков, которые формируются в процессе формального образования и закрепляются посредством получения квалификаций, некогнитивные навыки, как правило, не включённые в обязательные образовательные программы, играют ключевую роль в формировании общего человеческого капитала [@kuzminov2019]. Исследования всё чаще подчеркивают решающую роль этих навыков в обеспечении успеха на рынке труда, влияя как на возможности трудоустройства, так и на потенциальный уровень дохода — как в развитых [@ferguson2011; @almlund2011], так и в развивающихся странах [@nordman2015; @glewwe2022; @glewwe2017; @onsomu2025]. В отличие от когнитивных компетенций, некогнитивные навыки долгое время оставались вне фокуса экономического анализа, отчасти из-за отсутствия надёжных метрик, а отчасти из-за неопределённости в их теоретической классификации.

Некогнитивные навыки как термин и тема анализа инкорпорировались в программы исследований американских экономистов с середины 2000-х годов, что было сделано благодаря работам лауреата Нобелевской премии по экономике Джеймса Хекмана и его соавторов [@heckman2006; @heckman2008; @heckman2011]. Начиная с 2019 года, исследования эффекта некогнитивных навыков на экономические результаты индивидов появились и на российском контексте [@rozhkova2019; @maksimova2019; @gimpelson2020], что стало возможно благодаря включению блока соответствующего опросного модуля в Российский мониторинг экономического положения и здоровья населения (РМЭЗ), лонгитюдного исследования, проводимого Национальным Исследовательским Университетом "Высшая школа экономики" (НИУ ВШЭ) с 1994 года.

В то же время остаются концептуальные, методологические и политические вызовы: что именно мы считаем «некогнитивным навыком»? Являются ли личностные черты поддающимися целенаправленному развитию в рамках образовательной политики? И как обеспечить справедливость при оценке навыков, изначально зависящих от экономического положения семьи? Данные вопросы формируют повестку данного теоретического обзора.

Цель настоящей статьи - проанализировать концептуализацию некогнитивных навыков в экономических теориях человеческого капитала, оценить её применимость в рамках политики образования и занятости, а также систематизировать существующие подходы к измерению и классификации этих навыков. Иными словами, настоящая статья предлагает исторический разбор интеграции понятия некогнитивных навыков в экономическую теорию и прикладные исследования, обсуждает теоретические сложности определения и существующие таксономии, оценивает эмпирические данные о влиянии этих навыков на результаты в образовании и на рынке труда, включая российские исследования, и делает акцент на необходимости более точного операционального подхода, способного соединить академические исследования с задачами государственной политики в области образования и занятости.

## Концептуализация в экономике: как «ненаблюдаемые способности» стали экономическим активом?

Традиционные экономические модели, объясняющие различия в индивидуальных трудовых исходах, на протяжении десятилетий опирались на уровень образования и трудовой стаж как ключевые переменные. Наиболее распространённый подход — уравнение заработной платы Минсера — связывает уровень заработной платы с количеством лет обучения и трудового стажа [@mincer1974]. Однако даже базовый жизненный опыт подсказывает, что очень часто люди с одинаковым уровнем образования и опытом работы могут существенно разниться в оплате труда, что ставит под сомнение предиктивную валидность этих переменных как единственных и ключевых источников вариации в заработной плате. Сам Минсер и его последователи признавали существование множества других факторов, однако в рамках классического уравнения они оказывались в остаточном члене модели — как «ненаблюдаемые способности» \[unobserved abilities\].

На протяжении десятилетий наличие этих факторов признавалось, но не учитывалось из-за отсутствия подходящих данных. Основной индикатор человеческого капитала — продолжительность обучения — оставался лишь косвенным отражением качественных характеристик индивида. Однако с конца 1980-х годов ситуация начала меняться: стандартизированные тесты, административные данные и крупные репрезентативные обследования позволили впервые связать оценки когнитивных способностей с экономическими результатами [@hanushek2008]. Эти новые данные позволили оценить вклад когнитивных навыков — таких как математическая и языковая грамотность — в формирование заработной платы и индивидуальной продуктивности [@bishop1989a; @neal1996; @hanushek2000; @murnane2001]. Однако с учётом наличия корреляции между когнитивными способностями и образованием [@herrnstein1994], @heckman2001 указывает на трудности разделения этих эффектов друг от друга даже при наличии прямых метрик обеих характеристик.

Более того, даже с учётом когнитивных навыков значительная часть вариации в доходах оставалась необъяснённой. В ответ на это исследовательский фокус стал смещаться в сторону личностных характеристик как еще одной детерминанты индивидуальной гетерогенности. Концептуализированные экономистами как некогнитивные навыки, эти характеристики определяются как устойчивые паттерны мышления, эмоций и поведения [@borghans2008], формирующиеся в контексте социально-экономической среды, поддающиеся развитию с помощью обучающих программ, и способные приносить как экономическую, так и социальную ценность [@zhou2017]. Подход PES (productive, expandable, social) предлагает три критерия, по которым личностные характеристики могут трактоваться как навыки: они являются продуктивными (т.е. приносят ценность), поддаются развитию через тренинги и интервенции и, помимо генетики, формируются под влиянием социально-экономической среды [@green2013]. Такой взгляд позволяет рассматривать некогнитивные навыки как результат сложного взаимодействия между генетическими задатками и экономическими условиями социализации.

Идея о социальной обусловленности навыков и человеческого капитала в целом все больше находит подтверждение в науке благодаря устойчивому эконометрическому доказательству. Классическая работа еще одного Нобелевского лауреата по экономике, Р. Лукаса, говорит о том, что уровень навыков, получаемых индивидом в системе формального образования, зависит не только от качества самих общественных институтов, но и от других людей, формирующих его социальное окружение. Используя эконометрическую модель роста, основанную на данных о заработках в американской переписи населения, Лукас делает вывод, что человеческий капитал растет, когда индивид взаимодействует с более продуктивными людьми [@lucas2015].

Примечательно, что идея о значении личностных характеристик в передаче социального статуса и формировании экономического успеха не является новой. Ещё в 1970-х годах марксистские экономисты @bowles1976 в работе Schooling in Capitalist America утверждали, что формальное образование лишь отчасти определяет социальную мобильность: решающую роль играют такие качества, как дисциплина, исполнительность и склонность к подчинению социальным нормам. Более того, авторы указывали, что ценности, которые работодатели ищут в работниках, соответствуют тем, которые педагоги поощряют в учениках, артикулируя особую роль институтов образования и рынка труда в воспроизводстве экономического неравенства. Похожим образом несколько лет спустя @jencks1979 показали, что черты характера — например, трудолюбие или лидерские качества — могут оказывать влияние на доходы, сопоставимое с влиянием IQ или уровня образования родителей.

Долгие годы этот тезис оставался на периферии экономической науки, поскольку измерение личности считалось прерогативой психологии. Однако в начале 2000-х годов интерес к теме вернулся: @bowles2002 в ретроспективной работе подчеркнули, что социально-экономические преимущества передаются не только через образование и материальные ресурсы, но и через некогнитивные механизмы — от воспитания и наследуемых моделей мышления и поведения до доступности социальных связей.

Решающим моментом в признании экономической значимости некогнитивных навыков стали работы Джеймса Хекмана и его последователей. В фундаментальном исследовании авторы показали, что личностные характеристики оказывают влияние на заработную плату не меньшее, а в ряде случаев и большее, чем когнитивные способности [@heckman2006]. Кроме того, эти навыки влияют на образовательный выбор, мотивацию к обучению, устойчивость к стрессу, поведение на рабочем месте и адаптацию к изменяющимся условиям труда.

## Сложности дефиниции: почему они «не-когнитивные» и что с этим не так?

Несмотря на широкое распространение термина «некогнитивные навыки» в экономической литературе, в других дисциплинах, особенно в психологии — области, из которой этот концепт исторически происходит, он вызывает значительные споры и критику. В отличие от относительно однозначного понимания природы когнитивных навыков, определение того, какие именно навыки считаются некогнитивными, остаётся сложным и противоречивым [@cabus2021]. Один из наиболее распространённых подходов к их определению — подход исключения \[exclusion approach\], согласно которому некогнитивные навыки определяются как всё, что не является когнитивными [@messick1979]. Помимо сугубо методологической сложности, когда понятие определяется не через четко указанные антецеденты, а через то, чем оно не является, этот подход подвергается обоснованной критике за создание ложной дихотомии [@duckworth2015; @farrington2012], так как на практике паттерны мышления и поведения, оформленные в личностных чертах, не могут исключать когнитивные механизмы.

В связи с этим в современной литературе употребляется множество терминов, отражающих стремление преодолеть ограниченность исходного понятия. Среди них — «социально-эмоциональные навыки» [@attanasio2020], «навыки XXI века», «трансверсальные навыки» [@cinque2021] и «мягкие навыки» (soft skills) [@heckman2012; @koch2015; @laker2011]. Хотя Джеймс Хекман, один из пионеров экономического анализа данной темы, преимущественно использует термин «некогнитивные навыки», он также нередко называет их «социально-эмоциональными» и рассматривает оба термина как взаимозаменяемые [@heckman2016; @cunha2007; @heckman2013].

Тем не менее, несмотря на критику термина, его использование сохраняется прежде всего в экономической литературе — как удобный способ противопоставлять когнитивные навыки, измеряемые тестами на читательскую, математическую или естественно-научную грамотность вроде обследований PISA, TIMSS или PIRLS. В этом контексте «некогнитивные» навыки скорее представляют собой зонтичный термин, охватывающий всё, что связано с личностными чертами, социальным поведением и эмоциональной регуляцией — то есть теми характеристиками, которые важны для успеха в системе образования и на рынке труда, но не сводятся к интеллекту, знаниям или формально закрепленным квалификациям.

Разнообразие терминов и отсутствие единой системы классификации затрудняют как эмпирическое измерение этих навыков, так и сопоставимость результатов между различными исследованиями. Это подводит нас к следующей ключевой проблеме — отсутствию общепринятой таксономии некогнитивных навыков, что усложняет их операционализацию в научных и прикладных целях.

## Проблема таксономии: сколько граней у личности и как их уловить?

Несмотря на разногласия в определениях и подходах, наиболее распространённой и широко признанной системой классификации некогнитивных навыков остаётся пятифакторная модель личности \[Five Factor Model, FFM\], также известная как модель «Большой пятёрки» \[Big Five Inventory, BFI\] [@goldberg1990; @mccrae1987; @goldberg1990; @costa1992a; @costa1992b]. Её возникновение в конце 1980-х — начале 1990-х годов было обусловлено необходимостью научной систематизации индивидуальных различий в личности.

Ключевая идея модели «Большой пятёрки» состоит в том, что люди различаются между собой по устойчивым личностным характеристикам, которые сохраняются во времени и слабо подвержены ситуативным изменениям. Эти различия обобщаются по пяти независимым измерениям: открытость опыту \[Openness\], добросовестность \[Conscientiousness\], экстраверсия \[Extraversion\], доброжелательность \[Agreeableness\] и нейротизм \[Neuroticism\]. В совокупности они формируют модель, известную как OCEAN. Каждая из черт описывает континуум между двумя крайностями: открытость новому опыту варьируется от любопытства до осторожности, добросовестность — от организованности до беспечности, экстраверсия противопоставляется интроверсии, доброжелательность описывается на спектре от стремления к согласию до индивидуализма, а нейротизм противопоставлен эмоциональной стабильности. Важно подчеркнуть, что эти факторы понимаются как непрерывные переменные, подчиняющиеся нормальному распределению в популяции, а не как бинарные или ординальные характеристики, строго предписывающие индивиду ту или иную категорию [@john1999]. Это принципиально отличает FFM от типологических подходов, таких как MBTI (Myers-Briggs Type Indicator), классифицирующих индивидов по фиксированным типам [@myers1998].

Согласно логике FFM, за внешне сложным и многогранным человеческим поведением скрываются устойчивые и измеримые паттерны. Эта идея противопоставляется представлениям о ситуативной природе поведения, согласно которым личность — это, скорее, функция конкретного контекста, чем фиксированный набор характеристик. Основанием для модели «Большой пятёрки» стал лексикографический подход, корни которого восходят к работам Гордона Олпорта 1930-х годов [@allport1936]. Суть метода заключалась в том, что все значимые личностные черты должны находить отражение в языке — в тех словах (а именно прилагательных), которыми люди описывают друг друга в повседневной жизни. Статистический анализ показал, что большая часть прилагательных, используемых людьми как дескрипторы личностных характеристик, являются синонимами, что позволяет их группировать. Собрав максимальное количество таких дескрипторов из словарей, с помощью факторного анализа и группировки синонимов этот массив был сокращён и сведён к различным комбинациям факторов, которые в итоге легли в основу модели «Большой пятёрки».

Глоссарий Американской Психологической Ассоциации даёт определение каждой из этих черт, на которые впоследствии опирались @heckman2011 и его последователи в анализе некогнитивных навыков. Так, открытость определяется как черта, описывающая индивидуальные отличия в склонности к новому эстетическому, культурному и интеллектуальному опыту. Добросовестность описывает склонность быть организованным, ответственным и трудолюбивым; иногда она обозначается термином "работоспособность" [industriousness] и отражает нацеленность на результат. Экстраверсия характеризует ориентацию индивида на внешний мир людей и вещей в большей степени, чем на внутренний мир субъективного опыта. Доброжелательность выражается в склонности действовать кооперативно, руководствуясь принципами сотрудничества, а не собственными интересами. Эмоциональная стабильность, которая является обратной стороной нейротизма, указывает на предсказуемость и постоянство эмоциональных реакций, не сопровождающихся резкими перепадами настроения. Основываясь на работе @gough1983, @heckman2011 также соотносит черты «Большой пятёрки» с другими психологическими метриками, которые могут использоваться в качестве прокси. Так, добросовестность коррелирует с такими чертами, как упорство [grit], отложенное вознаграждение \[delayed gratification\] или самоконтроль; доброжелательность — с кооперацией, конкуренцией и эмпатией; эмоциональная стабильность и нейротизм — с локусом контроля, самооценкой \[self-esteem\] и самоэффективностью \[self-efficacy\].

Ранние психометрические измерения продемонстрировали ортогональность черт, предложенных в данной модели, то есть отсутствие взаимной корреляции между факторами, объясняющими пять ключевых источников вариации в описательных характеристиках личности на разных языках [@saucier2002]. Хотя последующие исследования [@hussey2020; @viswesvaran2000] поставили под сомнение полную независимость этих пяти факторов, психометрические характеристики данной модели по-прежнему превосходят альтернативные, что объясняет её популярность в психологии и поведенческих науках.

Тем не менее, модель «Большой пятёрки» не является единственным способом апроксимации некогнитивных навыков. В ряде экономических исследований используются иные метрики, такие как локус контроля Роттера [@rotter1966; @rotter1990] и шкала самооценки Розенберга [@rosenberg1965]. Локус контроля определяется как склонность личности приписывать свои достижения внутренним или внешним причинам. Экстернальный локус указывает на восприятие успехов и неудач как результата внешних обстоятельств, тогда как интернальный локус подразумевает, что источником результата служат внутренние усилия и качества индивида. Иными словами, данное понятие описывает степень восприятия контроля над собственной жизнью. Самооценка, в свою очередь, восходит к теории социолога Мориса Розенберга, который определял её как общее представление индивида о себе. В своих работах он трактовал самооценку подростков одновременно как функцию социального класса семьи и как значимый индивидуальный ресурс, влияющий на широкий спектр жизненных достижений.

Важно подчеркнуть, что первые исследования Джеймса Хекмана и его коллег, в частности фундаментальная работа о роли некогнитивных навыков в социальном поведении и на рынке труда [@heckman2006], опирались на локус контроля и самооценку, так как данные метрики были доступные в американском National Longitudinal Survey of Youth (NLSY) в 1979–1980 годах. Это определило не только выбор конкретных индикаторов, но и дало возможность включить личностное измерение в экономический анализ продуктивности, тем самым расширив границы традиционного подхода к человеческому капиталу.

## Влияние некогнитивных навыков на результаты на рынке труда: хороший человек - не профессия?

Критическая роль некогнитивных компонентов человеческого капитала подтверждена многочисленными эмпирическими замерами. Экономические исследования указывают, что эти характеристики влияют на результаты на рынке труда как напрямую, так и косвенно: экстраверсия и эмоциональная стабильность повышают успешность поиска работы, и эти эффекты часто опосредованы социальным капиталом [@baay2014]. Добросовестность предсказывает успех в карьере, в то время как нейротизм подрывает его [@judge1999]. Немецкие лонгитюдные данные показывают, что добросовестность сокращает периоды безработицы, тогда как нейротизм их увеличивает [@uysal2011]. Исследования человеческого капитала в уязвимых группах населения также подтверждают эти выводы. Среди мигрантов в Германии экстраверсия и открытость в большей степени предсказывают трудоустройство, чем у местных жителей, причём экстраверсия заменяет формальную квалификацию у менее образованных мигрантов [@akay2023].

Важность некогнитивных навыков обусловлена также тем, что они определяют как образовательные, так и профессиональные выборы индивидов, тем самым опосредованно влияя на их доходы [@roberts2007]. Например, лица с высоким уровнем экстраверсии чаще выбирают лидерские роли, а с высокой доброжелательностью — успешно работают в командах. Некогнитивные характеристики также влияют на рынок труда через механизмы найма: соискатели с высокой экстраверсией и добросовестностью и низким уровнем нейротизма воспринимаются работодателями более позитивно, что повышает их шансы на успешное трудоустройство.

Данные о влиянии на заработную плату неоднозначны в зависимости от социально-экономического контекста и разнятся от страны к стране. Метаанализ подтверждает межстрановую гетерогенность экономической отдачи от некогнитивных компонентов человеческого капитала [@cabus2021]. Таким образом, хотя отдача от некогнитивных навыков широко документирована, её величина варьируется в зависимости от пола, страны и сектора экономики. Административные данные Швеции (1992–2013 гг.) демонстрируют рост отдачи от некогнитивных навыков, особенно в частном секторе и для более высоких процентилей заработной платы [@edin2022]. Однако различия в измерениях некогнитивных навыков ограничивают сопоставимость исследований.

Работы на основе панельных исследований домохозяйств выявляют гендерные эффекты в экономической отдаче от некогнитивных компонентов человеческого капитала. Исследование на данных из Германии показываает, что доброжелательность снижает заработную плату женщин более чем на 6%, тогда как для мужчин этот эффект не обнаружен [@heineck2010]. При этом, другие характеристики показывают незначительный эффект после учета когнитивных навыков. В Великобритании открытость положительно предсказывает заработную плату, доброжелательность — отрицательно, нейротизм снижает заработок среди женщин, в то время как добросовестность демонстрирует нелинейный эффект [@heineck2011]. В США добросовестность, экстраверсия и IQ повышают заработную плату мужчин, но для женщин эффект показывает только экстраверсия [@gensowski2018].

## Тоже важны! Некогнитивные навыки в российской экономической литературе

Как уже было упомянуто выше, в российской экономической литературе исследования влияния некогнитивных навыков на различные аспекты социально-экономического поведения индивидов начали проводиться с 2019 года. Появление этих исследований стало возможным благодаря включению в РМЭЗ 2016 года блока из 24 вопросов, посвященных личностным характеристикам, опираясь на модель "Большой пятерки". Данный блок вопросов уже был использован в таких национально репрезентативных статистических обследованиях как German Socio-Economic Panel (SOEP) в Германии, Household, Income, and Labour Dynamics (HILDA) в Австралии, а также British Household Panel Survey (BHPS) в Великобритании. Использование данного инструментария в странах с низким или средним уровнем дохода было предпринято Всемирным банком в 2011-2017 году в сравнительном и национально-репрезентативном обследовании Skills toward Employment and Productivity (STEP).

Первые опубликованные исследования касались экономической отдачи от некогнитивных навыков. Результаты на российских данных подтвердили значимость некогнитивных характеристик для российского рынка труда, указав на особую роль открытости и эмоциональной стабильности в предсказании зарплатной премии [@rozhkova2019; @maksimova2019]. Данные результаты несколько отличаются от имеющихся в странах с высоким уровнем дохода, где эффекты данных характеристик были менее заметны. Более того, было выявлено, что некогнитивные навыки также частично объясняют гендерный разрыв в заработной плате, хотя их эффект не является сильно выраженным [@rozhkova2021b]. Исследование, основанное на дескриптивном анализе некогнитивных компонентов человеческого капитала в структуре российского населения, выявило существенное неравенство во владении этими навыками, наблюдаемое в срезе социально-демографических групп в зависимости от пола, возраста, уровня образования и сферы занятости [@gimpelson2020].

Постепенно фокус анализа некогнитивных навыков сместился с рынка труда на изучение эффектов этих характеристик в системе образования, или на стыке системы образования и рынка труда. Была подтверждена значимая роль некогнитивных навыков в принятии решений о получении высшего образования и выборе направления подготовки [@rozhkova2021a; @rozhkova2021c]. Анализ роли некогнитивных навыков в переходе от учебы к работе в России выявил, что добросовестность отрицательно коррелирует со статусом NEET - молодежи вне системы образования и занятости, в то время как нейротизм его увеличивает [@avanesian2024; @zudina2022].

Появление исследований на основе данных РМЭЗ побудило экономистов обратиться также к другим источникам данных и, как следствие, использованию других таксономий, изучая влияние некогнитивных навыков на академическую успеваемость школьников, с особым акцентом на школьников из экономически бедных семей. Подобными источниками стали данные PISA 2018 года в России и данные Исследования социально-эмоциональных навыков ОЭСР \[OECD Survey for Social and Emotional Skills\] в крупных городах мира (включая Москву) в 2019 году. Результаты показали, что учет некогнитивных навыков в образовании позволяет уменьшить негативный эффект бедности на академическую успеваемость, и инвестиции в развитие данных характеристик представляют эффективный способ поддержки формирования человеческого капитала среди экономически уязвимых слоев населения [@avanesian2022; @avanesian2025a].

В настоящий момент, когда помимо данных РМЭЗ 2016 года, выпущены также данные 2019 года, в российской экономической литературе накопился значительный пласт исследований, изучающих эффекты некогнитивных характеристик также на принятия решений о вакцинации [@roshchina2022; @roshchina2022a], здоровье и долголетие [@rozhkova2024], а также удовлетворенность работой как субъективного фактора успеха на рынке труда [@zudina2024]. Список потенциальных тем растет, как и доказательство важности роли некогнитивных характеристик в ряде социально-экономических результатов индивидов на примере российского контекста.

## Развивать или не вмешиваться? Этика и риски для системы государственного регулирования

Вопреки тому, что некогнитивные навыки всё чаще признаются важнейшим компонентом человеческого капитала и всё больше экономических исследований демонстрируют их долгосрочное влияние на занятость, образование и здоровье, интеграция данной академической повестки в комплекс мер государственного регулирования системы образования и рынка труда далека от простоты. Как уже было указано, в значительной части экономической литературы используется таксономия личности «Большой пятёрки» в качестве прокси некогнитивных навыков. При этом такие черты, как добросовестность, экстраверсия, эмоциональная стабильность, доброжелательность и открытость, рассматриваются как изначально желательные и социально одобряемые. Хотя эти черты могут статистически коррелировать с лучшими результатами на рынке труда, использование их в качестве целевого показателя политики в области образования и рынка труда проблематично. Личностные черты не являются навыками в строгом смысле этого слова — это относительно стабильные индивидуальные характеристики, сформированные как биологическими факторами, так и социальной средой. Поощрение всех учащихся или молодых работников к большей экстравертированности, доброжелательности или эмоциональной стабильности может привести к формированию узкой поведенческой нормативности, не учитывающей индивидуальные различия. Это особенно актуально в образовательных учреждениях, которые должны стремиться к созданию инклюзивной среды, где разнообразие темперамента и характера ценится, а не наказывается.

Важно отметить, что использование этих черт в качестве рычагов для политики в области образования и рынка труда может непреднамеренно закрепить на уровне институтов образования и рынка труда предубеждения в отношении субъективных характеристик, столь же дискриминационные, как и предубеждения, основанные на объективных характеристиках вроде пола, уровня богатства, статуса здоровья или этнической принадлежности. Например, хотя исследования могут показать, что экстраверты, как правило, более успешны на рынке труда, было бы ошибкой делать вывод, что системы образования должны активно развивать экстраверсию у всех учащихся. Вместо этого система государственного регулирования должна быть сосредоточена на конкретных навыках, связанных с экстраверсией, таких как коммуникация, работа в команде или публичные выступления, которые поддаются развитию и полезны для всех, независимо от глубинных особенностей личности человека.

Это приводит к более широкой и насущной проблеме: необходимости выйти за рамки личностных конструктов и перейти к более точной и применимой на практике таксономии некогнитивных навыков. Образовательная политика требует практических подходов, а не абстрактных психологических категорий. Современные модели личности, такие как «Большая пятёрка», предлагают полезные описательные инструменты, но им не хватает конкретики и гибкости, необходимых для разработки учебных программ, оценок и мер вмешательства. Необходима переклассификация некогнитивных черт в теоретическую рамку, которая чётко определяет, какие модели поведения и компетенции могут быть развиты и измерены в системе формального образования.

Создание такой таксономии позволит на практическом уровне управления системой образования формулировать конкретные цели обучения, связанные с социально-эмоциональным развитием, подобно тому, как они это делают для развития грамотности или навыков счёта. Это, в свою очередь, проложит путь к разработке более целенаправленных, валидных и контекстно-зависимых инструментов измерения. Только достигнув консенсуса относительно того, что представляет собой некогнитивный «навык» и чем он отличается от фиксированной черты, можно разработать осмысленные, справедливые и полезные оценки для отслеживания прогресса или оценки мер вмешательства. Данный аспект также позволяет идентифицировать направление для будущих исследований в данной области.

## Куда дальше? Направления будущих исследований

Несмотря на растущее внимание к некогнитивным навыкам в экономике и поведенческих науках, в нашем понимании данного феномена сохраняется ряд критических пробелов, требующих более глубокого изучения. Одним из важных направлений будущих исследований является изучение изменчивости некогнитивных навыков с течением времени. Cущественное ограничение заключается в том, что наиболее часто используемые инструменты для измерения некогнитивных навыков основаны на относительно коротких шкалах вроде сокращенного опросника «Большой пятёрки» и могут быть недостаточно чувствительными для выявления значимых изменений с течением времени. Примером тому являются две на сегодняшний момент фундаментальные работы в экономике, в которых стабильность некогнитивных навыков во времени была протестирована на сокращенном инструментарии [@cobb-clark2012; @cobb-clark2011]. Таким образом, наблюдаемая стабильность некогнитивных черт может быть, по крайней мере отчасти, функцией ограничений измерения, а не истинным отражением устойчивости черт. Поэтому будущие исследования должны быть сосредоточены не только на увеличении временного охвата панельных данных, но и на совершенствовании инструментов измерения, способных фиксировать более тонкие внутри-индивидуальные изменения некогнитивных навыков на протяжении жизни.

Другое важное направление заключается в уточнении эконометрических методов оценки эффектов некогнитивных навыков. Хотя большинство существующих исследований делают акцент на усреднённых эффектах, часто оценивая эластичность в линейных или лог-линейных моделях, появляется всё больше эмпирических данных о том, что связь между некогнитивными навыками и социально-экономическими результатами индивидов на рынке труда и в системе образования носит нелинейный характер. Данные исследования проводились в том числе и на российском материале, подтверждая валидность данной гипотезы и необходимость не ограничиваться средними эффектами [@avanesian2025; @avanesian2025a]. Будущие исследования должны включать гибкие стратегии моделирования, которые позволяют учитывать нелинейные зависимости и гетерогенные эффекты. Например, влияние добросовестности или эмоциональной стабильности может не увеличиваться монотонно, а стабилизироваться или даже измениться на противоположный. Не менее важно выйти за рамки анализа, основанного на средних значениях, и изучить, как влияние некогнитивных черт варьируется в зависимости от распределения результатов, таких как уровень заработной платы или удовлетворенности работой, используя квантильные регрессии и аналогичные подходы.

Кроме того, хотя основополагающие исследования Хекмана показали, что интервенции в развитие человеческого капитала в детском возрасте является более эффективным с точки зрения долгосрочной отдачи для общества и государства [@heckman2008], мало что известно о возможности влияния на эти черты на более поздних этапах развития, особенно в сфере высшего образования. В контексте как международной, так и российской литературы эта область остается в значительной степени малоизученной, с достаточно противоречивыми результатами [@sanginabadi2020; @kassenboehmer2018]. Понимание роли ВУЗов в развитии социально-эмоциональных компетенций может открыть новые пути для улучшения перехода молодежи на рынок труда, особенно в социально-экономических системах, где высшее образование имеет высокую отдачу.

## Заключение

Некогнитивные навыки — это не второстепенное дополнение к человеческому капиталу, а его ключевое измерение, отражающее поведенческие, мотивационные и адаптационные ресурсы личности. Экономическая литература последних лет убедительно демонстрирует их влияние на образование, занятость, доходы и здоровье.

Тем не менее, для интеграции некогнитивных характеристик в комплекс мер государственного регулирования системы образования и рынка труда необходимо перейти от абстрактных черт к прикладным компетенциям, пригодным для развития, оценки и интервенций. В этом плане психометрические модели личности, такие как «Большая пятёрка», являясь пригодными для академического дискурса, имеют ограничивает потенциал в прикладной плоскости.

Настоящий обзор подчеркивает необходимость переосмысления как понятийного аппарата, так и операциональных инструментов измерения. Будущие исследования должны быть сосредоточены на измерении динамики этих навыков во времени, их нелинейных и гетерогенных эффектов, а также роли институтов профессионального образования в их формировании. Только при наличии точной и контекстуальной таксономии мы сможем превратить знания о личностных характеристиках в действенные инструменты социальной политики.

## Список литературы {#refs}