# Заключение

## Основные выводы

\begingroup\color{red}

В настоящей диссертации была поставлена цель оценить, как некогнитивные навыки формируют ранние траектории молодежи на рынке труда в России. Ключевой аргумент работы состоит в том, что некогнитивные навыки следует рассматривать не только в качестве дополнительного набора характеристик, которые выражают индивидуальную неоднородность через наблюдаемые личностные метрики и предсказывают результаты индивидов на рынке труда. Напротив, ключевой теоретический вклад работы состоит в том, что она расширяет понимание некогнитивных навыков как контекстно-зависимых механизмов, через которые индивид конвертирует личностные диспозиции, образовательные ресурсы и исходные преимущества социально-экономического положения в различные показатели успеха на рынке труда. Эмпирические результаты показывают, что эффекты некогнитивных навыков не являются универсальными, а, напротив, отличаются в зависимости от изучаемого показателя и положения работника в распределении заработной платы, а также опосредуются предопределенными условиями вроде социально-экономического статуса, уровня образования, пола и др.  

Исследование рассматривает эти проблемы в три этапа. Первый этап анализировал, связаны ли некогнитивные навыки с формальной занятостью и ее характеристиками. Второй ставил целью установить, является ли отдача от некогнитивных навыков неоднородной в зависимости от положения молодого работника в распределении заработной платы. А третий этап расширил анализ, перейдя от объективных показателей к субъективному восприятию качества занятости как важному результату на рынке труда. Взятые вместе, эти три этапа позволяют оценить некогнитивные навыки не просто как предикторы занятости, а как механизмы, через которые оперируют более критические процессы интеграции на рынке труда для молодежи в начале карьеры: доступ к рабочим местам, экономическая ценность работы, а также ее субъективная оценка.

Первым ключевым результатом диссертации является вывод, что черты вроде добросовестности и экстраверсии устойчиво предсказывают формальную занятость молодежи. Эти результаты важны, так как фиксируют два отличных поведенческих механизма: добросовестность отражает упорство, самодисциплину, мотивацию к освоению задач и ориентацию на завершение начатого. В контексте молодежи в начале трудовой траектории эти черты могут повышать вероятность занятости, сигнализируя готовность к работе и потенциально снижая воспринимаемые работодателем риски найма. Экстраверсия, напротив, обозначает социальную активность, позитивный аффект и интенсивность социальных связей. Ее положительная связь с занятостью означает, что для отбора на рынке труда важно не только формальное образование, но также коммуникация и доступ к социальным сетям.

Второй важный результат диссертации заключается в том, что эффект некогнитивных навыков не является гомогенной, а зависит от контекстных факторов, оперирующих по принципу ex-ante, то есть до выхода индивида на рынок труда или до того, как тот или иной результат на рынке труда становится наблюдаемым. Иными словами, эффекты некогнитивных навыков варьируются по социально-экономическому статусу, уровню образования и полу. Указанные факторы выступают модераторами связи между некогнитивными навыками и результатами на рынке труда. Этот вывод является одним из центральных вкладов диссертации, который показывает, что некогнитивные навыки не оперируют в социальном вакууме. Их продуктивность контекстно-зависима и усиливается (или ослабевает) в соответствии с ресурсами и квалификациями, а также вписана в более широкую структуру неравенства возможностей, через которую личностные черты конвертируются в преимущества на рынке труда. В этом контексте особенно важным является факт, что когда эффекты от некогнитивных навыков выше для более привилегированных когорт молодежи, они по итогу усиливают преимущества этих групп через улучшение результатов на рынке труда. С другой стороны, некоторые некогнитивные навыки, напротив, могут оперировать через механизмы компенсации, то есть обладать большей продуктивностью когда сигналы от формальных компонентов человеческого капитала и ресурсы семьи ограничены.

Третий блок результатов касается качественных характеристик занятости. Результаты показывают, что открытость новому опыту положительно связана с вероятностью быть занятым в высококвалифицированных специальностях, основанных на умственном труде. Иными словами, продуктивность некогнитивных навыков меняется в зависимости от наблюдаемого показателя на рынке труда, что, в свою очередь, показывает, что их рыночная ценность не является универсальной. Открытость новому опыту, оперирующая через автономию, когнитивную гибкость и креативность, повышает вероятность занятости в сегментах, которые основаны на умственном труде и нерутинных профессиональных задачах.

Четвёртый важный результат работы говорит о том, что некогнитивные навыки также реализуются через механизмы профессионального соответствия, выступая каналами снижения рисков неэффективного использования человеческого капитала на рынке труда. Иными словами, среди молодежи с высшим образованием открытость отрицательно связана с вероятностью занятости в низкоквалифицированных должностях. Таким образом, некогнитивные навыки не просто способствуют занятости и выбору характера труда, но выступают как нематериальные активы, которые поддерживают конвертацию достижений в системе формального образования в более подходящее профессиональное положение на рынке труда. Этот результат важен, так как смещает интерпретацию некогнитивных навыков от узкой рамки трудоустройства к более широкой рамке профессионального соответствия и проблемам вертикального несоответствия и избыточного образования.

Пятый результат работы заключается в том, что отдача от некогнитивных навыков неоднородна в зависимости от позиции молодого работника в распределении заработной платы. Самый сильный и наиболее устойчивый эффект показывает открытость новому опыту, отдача от которой монотонно растет по мере увеличения оплаты труда. Эти выводы во многом подтверждают предыдущие результаты, показавшие, что открытость является важным предиктором занятости в профессиях, основанных на умственном труде, которые, в свою очередь, являются более высокооплачиваемыми. В целом результаты данного аналитического этапа показывают, что одни и те же некогнитивные навыки имеют разную экономическую ценность в зависимости от сегмента оплаты труда, варьируясь между низко-, средне- и высокооплачиваемыми молодыми работниками.

Шестой результат касается взаимоотношения некогнитивных навыков и формального образования в контексте отдачи от различных компонентов человеческого капитала. Модель заработной платы показывает, что эффекты некогнитивных навыков на заработную плату сокращаются после учета уровня образования, но не исчезают полностью. Этот результат соответствует теоретическому подходу, согласно которому образование является одним из каналов, через который некогнитивные навыки конвертируются в выигрыши на рынке труда. Устойчивость некоторых коэффициентов некогнитивных навыков после включения формального образования в модель показывает, что они являются больше, чем прокси образовательных траекторий индивида, обладая независимой предиктивной силой в отношении заработной платы и влияя на нее как напрямую, так и опосредованно, через образование.

Седьмой результат заключается в том, что некогнитивные навыки, будучи обобщением личностных характеристик человека, устойчиво связаны с субъективным восприятием качества занятости. Экстраверсия, эмоциональная стабильность и добросовестность положительно связаны с общей удовлетворенностью работой среди молодежи в начале карьеры. Это расширяет экономический анализ некогнитивных навыков с объективных и наблюдаемых результатов на рынке труда до внутренних и субъективных показателей качества занятости, показывая, что некогнитивные навыки не только важны в контексте работы и оплаты труда молодых людей, но и в контексте того, как они оценивают свое положение на рынке труда. Это особенно важно в контексте устойчивой и достойной занятости, которая не может быть сведена к формальному факту наличия работы. Удовлетворенность работой показывает, воспринимается ли профессиональный опыт как стабильный и соответствующий индивидуальным ожиданиям.

Восьмой результат показывает, что установленная связь между некогнитивными навыками и удовлетворённостью работой варьируется в зависимости от положения индивида в структуре оплаты труда. Иными словами, заработная плата опосредует эффект экстраверсии, эмоциональной стабильности и добросовестности на субъективное восприятие качества занятости. Одним из наиболее устойчивых результатов является вывод, что в низкооплачиваемых должностях, где объективные стимулы труда являются ограниченными, межличностная динамика рабочего места и атмосфера в коллективе будут факторами, ведущими к большей удовлетворенности у экстравертов. В целом результаты данного этапа анализа вносят вклад в понимание удовлетворенности работой как феномена, который не сводим ни к психологическим (акцентированным в диспозиционных теориях), ни к экономическим факторам (исследования в экономике, понимающие удовлетворенность работой как функцию объективных характеристик труда) в отдельности.

Наконец, еще один важный вывод, который можно сделать лишь по итогам всех трех этапов исследования. Из пяти личностных характеристик доброжелательность является единственной, которая не показала на уровне фиксированных эффектов предиктивной силы в отношении широкого спектра изучаемых в данной работе результатов молодежи на рынке труда. Как было описано ранее, доброжелательность оперирует через эмпатию, способность достичь компромисс и командную работу, описывая стремящихся к согласию людей в противоположность индивидуализму. Статистически значимые эффекты доброжелательности на формальную занятость были зафиксированы на уровне случайных коэффициентов среди молодых мужчин, а также среди молодежи со средним образованием или ниже. При этом, в указанных случаях эффект добросовестности умеренный, но отрицательный, и она уменьшает вероятность формальной занятости. Это означает, что рынок труда не вознаграждает (а иногда даже пенализирует) доброжелательность, так как, вероятно, молодые люди с высокой доброжелательностью слишком склонны к компромиссам и не в состоянии лоббировать свои интересы в пространстве конкуренции на рынке труда.

Главный вывод диссертации состоит в том, что некогнитивные навыки функционируют на рынке труда как социально встроенные ресурсы. Их ценность зависит от институционального и экономического контекста, в котором молодежь входит в сферу занятости и обусловливается такими характеристиками как уровень образования, социально-экономическое положение семьи, пол и другие. Важно понимать, что перечень возможных модераторов не ограничен теми, которые были использованы в данной работе. Однако это подводит к критическому заключению: некогнитивные навыки не могут быть в полной мере осмыслены в логике усредненных эффектов. Чтобы оценить их значимость для молодежной занятости, необходимо изучить, когда, для кого и при каких условиях рынка труда эти навыки становятся продуктивными. В этом и состоит эмпирический и теоретический вклад исследования.

\endgroup

## Значение для системы государственного регулирования

В целом, диссертация демонстрирует, что некогнитивные навыки важны для занятости молодежи в России. Интегрируя структурные, индивидуальные и субъективные аспекты результатов на рынке труда, она предлагает новое понимание того, как личностные характеристики влияют на результаты молодежи в сфере занятости. Тем не менее, хотя некогнитивные навыки всё чаще признаются ключевым элементом человеческого капитала, внедрение этой повестки в практику государственного регулирования остаётся непростым даже вопреки тому, что всё больше исследований подтверждает их устойчивое влияние не только на поведение на рынке труда, но и в таких областях, как образование и здоровье.

Главный вопрос в этом контексте предельно прост: когда и в кого инвестировать, чтобы обеспечить эффективность этих инвестиций для государства. Хотя исследование смотрит на молодежь в возрасте начиная с 15 лет, верифицированное строгими эконометрическими методами свидетельство в экономической литературе говорит нам о том, что программы развития некогнитивных навыков имеют наивысшую отдачу, если они сопровождают индивида в системе формального образования начиная с раннего детства [@heckman2006a]. В одной из широко известных программ в Северной Каролине, США, рекрутированные по рандомизированному принципу участники наблюдались с раннего детства до приблизительно 35 лет. Результаты программы показали существенные и долгосрочные эффекты на состояние здоровья, будущие доходы, снижение уровня преступности и рост образовательных достижений. Согласно эконометрическим оценкам, внутренняя норма доходности составила 13.7% в год, а соотношение выгод и затрат \[benefit/cost ratio\] достигло 7.3, то есть каждый вложенный доллар принес обществу 7.3 доллара совокупных выгод [@garcía2016]. Похожие выводы о необходимости развития некогнитивных навыков в раннем возрасте были также сделаны в ходе таких известных программ, как Perry Preschool Program и Abecedarian Program: опыт в детстве является основополагающим для производительности труда и индивидуального успеха во взрослом возрасте [@knudsen2006]. В этом отношении, хотя фокус настоящего диссертационного исследования сделан на молодежи от 15 до 29 лет, существующее эконометрическое доказательство указывает на неэффективность программ государственного регулирования, которые направляют чрезмерные инвестиции во взрослых с низким уровнем навыков и игнорируют детство как стадию, на которой инвестиции в человеческий капитал начинают приумножаться по принципу "навыки порождают навыки" [@heckman2006; @heckman2013].

Наконец, ответив на вопрос *"в кого и когда мы должны инвестировать"*, мы все-таки не отвечаем на вопрос *"что именно мы должны развивать?"*. Как уже было указано, в значительной части экономической литературы (и данное исследование не является исключением) используется таксономия личности «Большой пятёрки» в качестве прокси некогнитивных навыков. При этом такие черты, как добросовестность, экстраверсия, эмоциональная стабильность, доброжелательность и открытость новому опыту, рассматриваются как изначально желательные, социально одобряемые и продуктивные характеристики. Хотя эти черты могут статистически коррелировать с лучшими результатами на рынке труда, использование их в качестве целевого показателя политики в области образования и рынка труда проблематично. Личностные черты не являются навыками в строгом смысле этого слова — это относительно стабильные индивидуальные характеристики, сформированные как биологическими факторами, так и социальной средой. Поощрение всех учащихся или молодых работников к большей экстраверсии, доброжелательности или эмоциональной стабильности может привести к формированию узкой поведенческой нормативности, не учитывающей индивидуальные личностные различия, обусловленные в том числе темпераментом, работой мозга и функционированием нервной системы человека. Это особенно актуально в образовательных учреждениях, которые должны стремиться к созданию инклюзивной среды, где разнообразие личностных типажей и характеров должно цениться, а не наказываться.

Важно отметить, что использование этих черт в качестве рычагов для государственного регулирования может непреднамеренно закрепить на уровне институтов образования и рынка труда предубеждения в отношении субъективных характеристик, столь же дискриминационные, как и предубеждения, основанные на объективных характеристиках вроде пола, уровня богатства, статуса здоровья или этнической принадлежности. Например, хотя исследования могут показать, что экстраверты, как правило, более успешны на рынке труда, было бы ошибкой делать вывод, что системы образования должны активно развивать экстраверсию у всех учащихся. Вместо этого система государственного регулирования должна быть сосредоточена на конкретных навыках, производных от экстраверсии, таких как коммуникация, работа в команде или публичные выступления, которые поддаются развитию и полезны для всех, независимо от глубинных особенностей личности человека.

Даже такая черта, как добросовестность, столь активно культивируемая в системе образования еще с советских времен, в теоретической рамке пятифакторной модели личности является тесно связанной с нейрофизиологическими особенностями человека. Современные исследования в области нейровизуализации подтвердили, что это единственная личностная характеристика, которая демонстрирует робастные ассоциации с плотностью кортикальных участков головного мозга [@lewis2018]. Целенаправленный отбор по этой характеристике (и остальным чертам пятерки) будет неизбежно приводить к дискриминации по критериям, которые в значительной степени находятся вне контроля индивида.

Это приводит к более широкой и насущной проблеме: необходимости выйти за рамки личностных конструктов и перейти к более точной и применимой на практике таксономии некогнитивных навыков. Образовательная политика требует практических подходов, а не абстрактных психологических категорий. Современные модели личности, такие как «Большая пятёрка», предлагают полезные описательные инструменты, но им не хватает конкретики и гибкости, необходимых для разработки учебных программ, оценок и мер вмешательства. Необходима переклассификация некогнитивных способностей в теоретическую рамку, которая чётко определяет, какие модели поведения и компетенции могут быть развиты и измерены в системе формального образования.

Создание такой таксономии позволит на практическом уровне управления системой образования формулировать конкретные цели обучения, связанные с некогнитивным развитием, подобно тому, как они это делают для развития грамотности или навыков счёта. Это, в свою очередь, проложит путь к разработке более целенаправленных, валидных и контекстно-зависимых инструментов измерения. Только достигнув консенсуса относительно того, что представляет собой некогнитивный «навык» и чем он отличается от фиксированной черты, мы сможем разработать осмысленные, справедливые и полезные оценки для отслеживания прогресса или оценки мер вмешательства.

Подводя итог, можно сказать, что, хотя экономические данные о некогнитивных навыках убедительны, их использование в комплексе мер государственного регулирования системы образования или рынка труда должно быть продуманным и осторожным. Практическим специалистам следует избегать упрощенных интерпретаций результатов, основанных на личностных характеристиках, и вместо этого инвестировать в создание практичной, ориентированной на навыки таксономии, которая принимает во внимание индивидуальные различия, одновременно помогая молодежи приобретать социальные, эмоциональные и поведенческие компетенции, необходимые для успеха в учебе, работе и жизни. Указанное также позволяет идентифицировать направление для будущих исследований в данной области.

## Ограничения исследования

Настоящее исследование имеет ряд ограничений, которые необходимо принять во внимание для корректной интерпретации полученных результатов. Эти ограничения касаются используемого инструментария измерения некогнитивных навыков, качества данных и пропущенных значений. `\textcolor{red}{Методологические особенности ограничений, обусловленных стратегией экономической верификации, были представлены в работе ранее, поэтому в данном разделе не рассматриваются.}`{=latex}

`\textcolor{red}{Во-первых, следует отметить ограничения, связанные с общей выборкой РМЭЗ, которая считается смещенной в сторону респондентов с низкими доходами, более охотно участвующими в обследовании. Поэтому полученные оценки могут не учитывать характер связи некогнитивных навыков и анализируемых исходов в высокодоходных группах молодежи.}`{=latex}

Во-вторых, следует отметить ограничения, связанные с измерением некогнитивных характеристик. Используемая шкала, несмотря на её международную апробацию и соответствие инструментам, применяемым в ряде международных опросов, представляет собой сокращённую версию теста на черты личности «Большой пятёрки». В российской психологической литературе чаще в качестве валидного инструмента используется альтернативный, более полный опросник. Таким образом, хотя полученные результаты могут быть сопоставимы с зарубежными исследованиями, использующими аналогичный укороченный модуль, психометрические свойства шкал, включая чувствительность, валидность и надёжность, могут быть ограничены в российском контексте. Это может повлиять на способность инструмента фиксировать как индивидуальные различия, так и изменения некогнитивных характеристик во времени, что следует признать уже на ранних этапах анализа.

В-третьих, на точность измерения некогнитивных характеристик может влиять склонность респондентов отвечать на психометрические тесты в социально одобряемом ключе \[social desirability bias\]. Известно, что такие эффекты — в частности, искажения ответов на основании стремления представить себя в позитивном свете — широко обсуждаются в литературе, особенно в контексте опросников «Большой пятёрки». В более широком контексте подвергается сомнению валидность суждения индивидов о своих некогнитивных навыках через самоотчётные тесты \[self-reported tests\] и необходимость либо триангуляции результатов, либо предложения других механизмов оценки, вроде проектных задач. Это вносит потенциальное смещение, которое затрудняет интерпретацию индивидуальных характеристик как объективно фиксируемых и устойчивых поведенческих черт.

Четвёртое ограничение связано непосредственно с качеством данных. Пропуски в ответах на вопросы, касающиеся доходов, и частичный отказ респондентов от прохождения модуля по некогнитивным навыкам существенно сокращают объём наблюдений и могут приводить к смещению выборки. Это, в свою очередь, ставит под сомнение репрезентативность полученных результатов. Такие ограничения подчёркивают необходимость использования процедур взвешивания или методов псевдослучайной рандомизации, компенсирующих дисбаланс в структуре данных.

## Направления будущих исследований

Несмотря на растущее внимание к некогнитивным навыкам в экономике и поведенческих науках, в нашем понимании данного феномена сохраняется ряд критических пробелов, требующих более глубокого изучения. Одним из важных направлений будущих исследований является изучение изменчивости некогнитивных навыков с течением времени. Это требует чёткого разграничения двух часто смешиваемых исследовательских вопросов: во-первых, меняются ли личности людей при переходе от подросткового возраста к взрослой жизни и на более поздние этапы жизни, и если да, то как и в какой степени; и во-вторых, как различаются средние уровни некогнитивных навыков в разных возрастных группах в определённый момент времени. Первый вопрос требует лонгитюдного подхода, позволяющего изолировать внутри-индивидуальные изменения и отслеживать траектории развития в течение нескольких лет, в идеале превышающих стандартный четырёхлетний период исследования. Второй вопрос, напротив, может быть решён с использованием достаточно больших кросс-секционных наборов данных, которые позволяют выявить статистически значимые различия между возрастными когортами.

Однако даже в исследованиях, использующих внутри-индивидуальный дизайн эконометрической верификации, сохраняется существенное ограничение: наиболее часто используемые инструменты для измерения некогнитивных навыков основаны на относительно коротких шкалах вроде сокращенного опросника «Большой пятёрки», которые могут быть недостаточно чувствительными для выявления значимых изменений с течением времени. Таким образом, наблюдаемая стабильность некогнитивных навыков может быть, по крайней мере, отчасти функцией ограничений измерения, а не истинным отражением устойчивости этих черт. Поэтому будущие исследования должны быть сосредоточены не только на увеличении временного охвата панельных данных, но и на совершенствовании инструментов измерения, способных фиксировать более тонкие внутри-индивидуальные изменения некогнитивных навыков на протяжении жизни.

Другое важное направление заключается в уточнении методов моделирования эффектов некогнитивных навыков. Хотя большинство существующих исследований делают акцент на усреднённых эффектах, часто оценивая эластичность в линейных или лог-линейных моделях, появляется всё больше эмпирических данных, в том числе и в настоящем исследовании, о том, что связь между некогнитивными навыками и социально-экономическими результатами индивидов на рынке труда и в системе образования носит нелинейный характер. Будущие исследования должны включать гибкие стратегии моделирования, которые позволяют учитывать нелинейные зависимости и гетерогенные эффекты. Например, эффект добросовестности или эмоциональной стабильности может не увеличиваться монотонно, а стабилизироваться или даже измениться на противоположный. Не менее важно выйти за рамки анализа, основанного на средних значениях, и изучить, как эффект некогнитивных способностей варьируется в зависимости от распределения результатов, таких как удовлетворенность работой, уровень заработной платы или вероятность трудоустройства, используя квантильные регрессии и аналогичные подходы.

Кроме того, хотя основополагающие исследования Дж. Хекмана и других показали, что раннее вмешательство в детском возрасте дает высокие результаты в формировании некогнитивных навыков, мало что известно о возможности влияния на эти черты на более поздних этапах развития, особенно в сфере высшего образования. В контексте как международной, так и российской литературы эта область остается в значительной степени малоизученной. Понимание роли ВУЗов в развитии социально-эмоциональных компетенций может открыть новые пути для улучшения `\textcolor{red}{условий выхода молодежи на рынок труда}`{=latex}, особенно в экономиках, где высшее образование имеет высокую отдачу.

Наконец, как подчёркивается в данном исследовании, социально-экономическое положение, особенно условия рождения и раннего периода жизни, оказывает мощное влияние на формирование некогнитивных навыков. Поэтому семью, как основной институт ранней социализации, следует рассматривать не только как контекст, в котором развиваются эти навыки, но и как потенциальный агент изменения. Однако до сих пор наблюдается дефицит эмпирических работ, систематически изучающих внутрисемейные механизмы, лежащие в основе развития некогнитивных навыков, с учётом как генетической наследственности, так и общих факторов окружающей среды. Для этого необходимо применение внутрисемейного дизайна (например, с использованием данных о братьях и сёстрах), что позволит разделить влияние факторов, индивидуально-специфичных для каждого ребёнка, и общих факторов на уровне семьи. Этот вектор анализа, которым уже занимается автор, может обеспечить приращение нового знания о внутрисемейной динамике формирования некогнитивных способностей и способствовать разработке семейно-ориентированной политики, направленной на сокращение неравенства в человеческом капитале с самых ранних этапов жизни.

{{< pagebreak >}}